# Generated by Django 3.2.2 on 2021-05-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='company',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на гитхаб компании'),
        ),
    ]
