# Generated by Django 3.2.2 on 2021-05-16 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='core.userprofile', verbose_name='Работодатель'),
        ),
    ]
