# Generated by Django 3.2.2 on 2021-06-01 16:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import jobseeker.resume.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('profile_picture', models.ImageField(blank=True, default='Default/avatar.jpg', null=True, upload_to=jobseeker.resume.models.Resume.load_photo, verbose_name='Фото')),
                ('background_picture', models.ImageField(blank=True, null=True, upload_to=jobseeker.resume.models.Resume.load_photo, verbose_name='Задний фон')),
                ('headline', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('short_description', models.TextField(max_length=400, verbose_name='Краткое описание')),
                ('location', models.CharField(max_length=75, verbose_name='Локация')),
                ('salary', models.CharField(max_length=75, verbose_name='Зарплата')),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('phone', models.CharField(max_length=75, verbose_name='Номер телефона')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Адрес вебсайта')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на фейсбук компании')),
                ('google_plus_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на гугл+ компании')),
                ('dribbble_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на дрибл компании')),
                ('pinterest_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на пинтерест компании')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на твиттер компании')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на гитхаб компании')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на инстаграм компании')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на ютуб компании')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания резюме')),
                ('jobseeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='core.userprofile', verbose_name='Резюме')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('date_from', models.DateField(verbose_name='Дата начала работы')),
                ('date_to', models.DateField(verbose_name='Дата завершения работы')),
                ('job_detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание')),
                ('resume', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Резюме')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название технологии')),
                ('proficiency', models.CharField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], default=10, max_length=75, null=True, verbose_name='Ученая степень')),
                ('resume', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Резюме')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Postdoc', 'Postdoc'), ('Doctor', 'Doctor')], default='Bachelor', max_length=75, null=True, verbose_name='Ученая степень')),
                ('major', models.CharField(max_length=100, verbose_name='Специальность')),
                ('school', models.CharField(max_length=100, verbose_name='Учебное заведение')),
                ('date_from', models.SmallIntegerField(verbose_name='Дата поступления')),
                ('date_to', models.SmallIntegerField(verbose_name='Дата окончания')),
                ('short_description', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('resume', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Резюме')),
            ],
        ),
    ]
