# Generated by Django 3.2.2 on 2021-05-18 11:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Название работы')),
                ('short_description', models.TextField(max_length=400, verbose_name='Краткое описание')),
                ('application_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на вакансию')),
                ('location', models.CharField(max_length=75, verbose_name='Локация')),
                ('type_of_employment', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Remote', 'Remote')], default='Full time', max_length=10, verbose_name='Вид трудоустройства')),
                ('salary', models.CharField(max_length=75, verbose_name='Зарплата')),
                ('working_hours', models.CharField(max_length=75, verbose_name='Часы работы')),
                ('experience', models.CharField(max_length=75, verbose_name='Опыт работы')),
                ('academic_degree', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Postdoc', 'Postdoc'), ('Doctor', 'Doctor')], default='', max_length=75, null=True, verbose_name='Ученая степень')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания объявления')),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('job_detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company')),
            ],
        ),
    ]
