# Generated by Django 3.2.2 on 2021-05-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Postdoc', 'Postdoc'), ('Doctor', 'Doctor')], default='Bachelor', max_length=75, null=True, verbose_name='Ученая степень'),
        ),
    ]
